### ISSUE TITLE
Box-Shadows overriding intended CSS spacing, even after manual trial and error to provide more space

### ISSUE THREAD

**Issue by Charlie-BR** [jortron/jsCalc#3]
Box-Shadows overriding the CSS padding, and while the px adjustments I've made make sense on the math side, my layout isn't matching - If I still want to display inline-block, how would I get the space between buttons? I've tried adjusting specific padding and margins on all sides of the elements but it's not working as expected.  Happy to hear about better approaches instead of using the CSS centering option!

```css
#buttonLeft {
border-size: 3px;
border-color: 7px;
margin: 3px;
padding: 3px;
border: 2em;
display: inline;
}
```
